language: go

go: 
 - "1.8"
 - "1.9"

install:
  - go get github.com/mattn/goveralls

script:
 - goveralls -service=travis-ci

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com
